# Generated by Django 5.2.5 on 2025-10-05 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'National ID Card'), ('DRIVERS_LICENSE', "Driver's License"), ('PASSPORT', 'International Passport')], default='NATIONAL_ID', max_length=28)),
                ('id_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Record',
                'verbose_name_plural': 'KYC Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
