# Generated by Django 5.2.5 on 2025-10-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
    ]
